name: Deploy to Local

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
      WP_URL: ${{ secrets.WP_URL }}
      WP_TITLE: ${{ secrets.WP_TITLE }}
      WP_ADMIN_USER: ${{ secrets.WP_ADMIN_USER }}
      WP_ADMIN_PASSWORD: ${{ secrets.WP_ADMIN_PASSWORD }}
      WP_ADMIN_EMAIL: ${{ secrets.WP_ADMIN_EMAIL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        run: |
          docker compose down
          docker compose up -d --remove-orphans
          docker image prune -f
